#ifndef LIBXCOM_PARAMETER_TRAITS_H
#define LIBXCOM_PARAMETER_TRAITS_H
#include <cmath>
#include <ixcom/XCOMdat.h>
#include <type_traits>
// This file is automatically generated, DO NOT EDIT.
template<typename>
struct ParameterTraits;
template<>
struct ParameterTraits<XCOMParSYS_PRJNUM> {
    static constexpr uint16_t Id = XCOMPAR_PARSYS_PRJNUM;
};
template<>
struct ParameterTraits<XCOMParSYS_PARTNUM> {
    static constexpr uint16_t Id = XCOMPAR_PARSYS_PARTNUM;
};
template<>
struct ParameterTraits<XCOMParSYS_SERIALNUM> {
    static constexpr uint16_t Id = XCOMPAR_PARSYS_SERIALNUM;
};
template<>
struct ParameterTraits<XCOMParSYS_MFG> {
    static constexpr uint16_t Id = XCOMPAR_PARSYS_MFG;
};
template<>
struct ParameterTraits<XCOMParSYS_CALDATE> {
    static constexpr uint16_t Id = XCOMPAR_PARSYS_CALDATE;
};
template<>
struct ParameterTraits<XCOMParSYS_FWVERSION> {
    static constexpr uint16_t Id = XCOMPAR_PARSYS_FWVERSION;
};
template<>
struct ParameterTraits<XCOMParSYS_NAVLIB> {
    static constexpr uint16_t Id = XCOMPAR_PARSYS_NAVLIB;
};
template<>
struct ParameterTraits<XCOMParSYS_EKFLIB> {
    static constexpr uint16_t Id = XCOMPAR_PARSYS_EKFLIB;
};
template<>
struct ParameterTraits<XCOMParSYS_EKFPARSET> {
    static constexpr uint16_t Id = XCOMPAR_PARSYS_EKFPARSET;
};
template<>
struct ParameterTraits<XCOMParSYS_NAVNUM> {
    static constexpr uint16_t Id = XCOMPAR_PARSYS_NAVNUM;
};
template<>
struct ParameterTraits<XCOMParSYS_NAVPARSET> {
    static constexpr uint16_t Id = XCOMPAR_PARSYS_NAVPARSET;
};
template<>
struct ParameterTraits<XCOMParSYS_MAINTIMING> {
    static constexpr uint16_t Id = XCOMPAR_PARSYS_MAINTIMING;
};
template<>
struct ParameterTraits<XCOMParSYS_PRESCALER> {
    static constexpr uint16_t Id = XCOMPAR_PARSYS_PRESCALER;
};
template<>
struct ParameterTraits<XCOMParSYS_UPTIME> {
    static constexpr uint16_t Id = XCOMPAR_PARSYS_UPTIME;
};
template<>
struct ParameterTraits<XCOMParSYS_OPERATIONHOUR> {
    static constexpr uint16_t Id = XCOMPAR_PARSYS_OPERATIONHOUR;
};
template<>
struct ParameterTraits<XCOMParSYS_BOOTMODE> {
    static constexpr uint16_t Id = XCOMPAR_PARSYS_BOOTMODE;
};
template<>
struct ParameterTraits<XCOMParSYS_FPGAVERSION> {
    static constexpr uint16_t Id = XCOMPAR_PARSYS_FPGAVERSION;
};
template<>
struct ParameterTraits<XCOMParSYS_CONFIGCRC> {
    static constexpr uint16_t Id = XCOMPAR_PARSYS_CONFIGCRC;
};
template<>
struct ParameterTraits<XCOMParSYS_OSVERSION> {
    static constexpr uint16_t Id = XCOMPAR_PARSYS_OSVERSION;
};
template<>
struct ParameterTraits<XCOMParSYS_SYSNAME> {
    static constexpr uint16_t Id = XCOMPAR_PARSYS_SYSNAME;
};
template<>
struct ParameterTraits<XCOMParSYS_MINFPGAVER> {
    static constexpr uint16_t Id = XCOMPAR_PARSYS_MINFPGAVER;
};
template<>
struct ParameterTraits<XCOMParSYS_SYNCMODE> {
    static constexpr uint16_t Id = XCOMPAR_PARSYS_SYNCMODE;
};
template<>
struct ParameterTraits<XCOMParSYS_CALIBID> {
    static constexpr uint16_t Id = XCOMPAR_PARSYS_CALIBID;
};
template<>
struct ParameterTraits<XCOMParSYS_EEPROM> {
    static constexpr uint16_t Id = XCOMPAR_PARSYS_EEPROM;
};
template<>
struct ParameterTraits<XCOMParSYS_GNSSTYPE> {
    static constexpr uint16_t Id = XCOMPAR_PARSYS_GNSSTYPE;
};
template<>
struct ParameterTraits<XCOMParSYS_GITSHA> {
    static constexpr uint16_t Id = XCOMPAR_PARSYS_GITSHA;
};
template<>
struct ParameterTraits<XCOMParSYS_GITBRANCH> {
    static constexpr uint16_t Id = XCOMPAR_PARSYS_GITBRANCH;
};
template<>
struct ParameterTraits<XCOMParSYS_CIPIPELINEID> {
    static constexpr uint16_t Id = XCOMPAR_PARSYS_CIPIPELINEID;
};
template<>
struct ParameterTraits<XCOMParSYS_USBCONFIG> {
    static constexpr uint16_t Id = XCOMPAR_PARSYS_USBCONFIG;
};
template<>
struct ParameterTraits<XCOMParIMU_MISALIGN> {
    static constexpr uint16_t Id = XCOMPAR_PARIMU_MISALIGN;
};
template<>
struct ParameterTraits<XCOMParIMU_TYPE> {
    static constexpr uint16_t Id = XCOMPAR_PARIMU_TYPE;
};
template<>
struct ParameterTraits<XCOMParIMU_REFPOINTOFFSET> {
    static constexpr uint16_t Id = XCOMPAR_PARIMU_REFPOINTOFFSET;
};
template<>
struct ParameterTraits<XCOMParIMU_BANDSTOP> {
    static constexpr uint16_t Id = XCOMPAR_PARIMU_BANDSTOP;
};
template<>
struct ParameterTraits<XCOMParIMU_SECONDARY> {
    static constexpr uint16_t Id = XCOMPAR_PARIMU_SECONDARY;
};
template<>
struct ParameterTraits<XCOMParGNSS_ANTOFFSET> {
    static constexpr uint16_t Id = XCOMPAR_PARGNSS_ANTOFFSET;
};
template<>
struct ParameterTraits<XCOMParGNSS_RTKMODE> {
    static constexpr uint16_t Id = XCOMPAR_PARGNSS_RTKMODE;
};
template<>
struct ParameterTraits<XCOMParGNSS_DUALANTMODE> {
    static constexpr uint16_t Id = XCOMPAR_PARGNSS_DUALANTMODE;
};
template<>
struct ParameterTraits<XCOMParGNSS_LOCKOUTSYSTEM> {
    static constexpr uint16_t Id = XCOMPAR_PARGNSS_LOCKOUTSYSTEM;
};
template<>
struct ParameterTraits<XCOMParGNSS_RTCMV3CONFIG> {
    static constexpr uint16_t Id = XCOMPAR_PARGNSS_RTCMV3CONFIG;
};
template<>
struct ParameterTraits<XCOMParGNSS_MODEL> {
    static constexpr uint16_t Id = XCOMPAR_PARGNSS_MODEL;
};
template<>
struct ParameterTraits<XCOMParGNSS_VERSION> {
    static constexpr uint16_t Id = XCOMPAR_PARGNSS_VERSION;
};
template<>
struct ParameterTraits<XCOMParGNSS_CORPORTCFG> {
    static constexpr uint16_t Id = XCOMPAR_PARGNSS_CORPORTCFG;
};
template<>
struct ParameterTraits<XCOMParGNSS_GATEWAYCFG> {
    static constexpr uint16_t Id = XCOMPAR_PARGNSS_GATEWAYCFG;
};
template<>
struct ParameterTraits<XCOMParGNSS_ANTENNAPOWER> {
    static constexpr uint16_t Id = XCOMPAR_PARGNSS_ANTENNAPOWER;
};
template<>
struct ParameterTraits<XCOMParGNSS_PPSCONTROL> {
    static constexpr uint16_t Id = XCOMPAR_PARGNSS_PPSCONTROL;
};
template<>
struct ParameterTraits<XCOMParGNSS_HDGOFFSET> {
    static constexpr uint16_t Id = XCOMPAR_PARGNSS_HDGOFFSET;
};
template<>
struct ParameterTraits<XCOMParGNSS_PERIOD> {
    static constexpr uint16_t Id = XCOMPAR_PARGNSS_PERIOD;
};
template<>
struct ParameterTraits<XCOMParGNSS_GGAQUALITY> {
    static constexpr uint16_t Id = XCOMPAR_PARGNSS_GGAQUALITY;
};
template<>
struct ParameterTraits<XCOMParMAG_PORT> {
    static constexpr uint16_t Id = XCOMPAR_PARMAG_PORT;
};
template<>
struct ParameterTraits<XCOMParMAG_RATE> {
    static constexpr uint16_t Id = XCOMPAR_PARMAG_RATE;
};
template<>
struct ParameterTraits<XCOMParMAG_MISALIGN> {
    static constexpr uint16_t Id = XCOMPAR_PARMAG_MISALIGN;
};
template<>
struct ParameterTraits<XCOMParMAG_CALSTATE> {
    static constexpr uint16_t Id = XCOMPAR_PARMAG_CALSTATE;
};
template<>
struct ParameterTraits<XCOMParMAG_FOM> {
    static constexpr uint16_t Id = XCOMPAR_PARMAG_FOM;
};
template<>
struct ParameterTraits<XCOMParMAG_ENABLE> {
    static constexpr uint16_t Id = XCOMPAR_PARMAG_ENABLE;
};
template<>
struct ParameterTraits<XCOMParMADC_ENABLE> {
    static constexpr uint16_t Id = XCOMPAR_MADC_ENABLE;
};
template<>
struct ParameterTraits<XCOMParMADC_LEVERARM> {
    static constexpr uint16_t Id = XCOMPAR_MADC_LEVERARM;
};
template<>
struct ParameterTraits<XCOMParMADC_LOWPASS> {
    static constexpr uint16_t Id = XCOMPAR_MADC_LOWPASS;
};
template<>
struct ParameterTraits<XCOMParREC_CONFIG> {
    static constexpr uint16_t Id = XCOMPAR_REC_CONFIG;
};
template<>
struct ParameterTraits<XCOMParREC_START> {
    static constexpr uint16_t Id = XCOMPAR_REC_START;
};
template<>
struct ParameterTraits<XCOMParREC_STOP> {
    static constexpr uint16_t Id = XCOMPAR_REC_STOP;
};
template<>
struct ParameterTraits<XCOMParREC_POWERLOGGER> {
    static constexpr uint16_t Id = XCOMPAR_REC_POWERLOGGER;
};
template<>
struct ParameterTraits<XCOMParREC_SUFFIX> {
    static constexpr uint16_t Id = XCOMPAR_REC_SUFFIX;
};
template<>
struct ParameterTraits<XCOMParREC_DISKSPACE> {
    static constexpr uint16_t Id = XCOMPAR_REC_DISKSPACE;
};
template<>
struct ParameterTraits<XCOMParREC_AUXILIARY> {
    static constexpr uint16_t Id = XCOMPAR_REC_AUXILIARY;
};
template<>
struct ParameterTraits<XCOMParREC_CURRENTFILE> {
    static constexpr uint16_t Id = XCOMPAR_REC_CURRENTFILE;
};
template<>
struct ParameterTraits<XCOMParREC_LOGROTATE> {
    static constexpr uint16_t Id = XCOMPAR_REC_LOGROTATE;
};
template<>
struct ParameterTraits<XCOMParREC_DEVICE> {
    static constexpr uint16_t Id = XCOMPAR_REC_DEVICE;
};
template<>
struct ParameterTraits<XCOMParREC_FILESIZE> {
    static constexpr uint16_t Id = XCOMPAR_REC_FILESIZE;
};
template<>
struct ParameterTraits<XCOMParREC_MOTION> {
    static constexpr uint16_t Id = XCOMPAR_REC_MOTION;
};
template<>
struct ParameterTraits<XCOMParEKF_ALIGNMODE> {
    static constexpr uint16_t Id = XCOMPAR_PAREKF_ALIGNMODE;
};
template<>
struct ParameterTraits<XCOMParEKF_ALIGNTIME> {
    static constexpr uint16_t Id = XCOMPAR_PAREKF_ALIGNTIME;
};
template<>
struct ParameterTraits<XCOMParEKF_COARSETIME> {
    static constexpr uint16_t Id = XCOMPAR_PAREKF_COARSETIME;
};
template<>
struct ParameterTraits<XCOMParEKF_VMP> {
    static constexpr uint16_t Id = XCOMPAR_PAREKF_VMP;
};
template<>
struct ParameterTraits<XCOMParEKF_AIDING> {
    static constexpr uint16_t Id = XCOMPAR_PAREKF_AIDING;
};
template<>
struct ParameterTraits<XCOMParEKF_DELAY> {
    static constexpr uint16_t Id = XCOMPAR_PAREKF_DELAY;
};
template<>
struct ParameterTraits<XCOMParEKF_STARTUP> {
    static constexpr uint16_t Id = XCOMPAR_PAREKF_STARTUP;
};
template<>
struct ParameterTraits<XCOMParEKF_HDGPOSTHR> {
    static constexpr uint16_t Id = XCOMPAR_PAREKF_HDGPOSTHR;
};
template<>
struct ParameterTraits<XCOMParEKF_SMOOTH> {
    static constexpr uint16_t Id = XCOMPAR_PAREKF_SMOOTH;
};
template<>
struct ParameterTraits<XCOMParEKF_ZUPT> {
    static constexpr uint16_t Id = XCOMPAR_PAREKF_ZUPT;
};
template<>
struct ParameterTraits<XCOMParEKF_ZUPT2> {
    static constexpr uint16_t Id = XCOMPAR_PAREKF_ZUPT2;
};
template<>
struct ParameterTraits<XCOMParEKF_DEFPOS> {
    static constexpr uint16_t Id = XCOMPAR_PAREKF_DEFPOS;
};
template<>
struct ParameterTraits<XCOMParEKF_DEFHDG> {
    static constexpr uint16_t Id = XCOMPAR_PAREKF_DEFHDG;
};
template<>
struct ParameterTraits<XCOMParEKF_OUTLIER> {
    static constexpr uint16_t Id = XCOMPAR_PAREKF_OUTLIER;
};
template<>
struct ParameterTraits<XCOMParEKF_POWERDOWN> {
    static constexpr uint16_t Id = XCOMPAR_PAREKF_POWERDOWN;
};
template<>
struct ParameterTraits<XCOMParEKF_EARTHRAD> {
    static constexpr uint16_t Id = XCOMPAR_PAREKF_EARTHRAD;
};
template<>
struct ParameterTraits<XCOMParEKF_STOREDPOS> {
    static constexpr uint16_t Id = XCOMPAR_PAREKF_STOREDPOS;
};
template<>
struct ParameterTraits<XCOMParEKF_ALIGNZUPTSTDDEV> {
    static constexpr uint16_t Id = XCOMPAR_PAREKF_ALIGNZUPTSTDDEV;
};
template<>
struct ParameterTraits<XCOMParEKF_POSAIDSTDDEVTHR> {
    static constexpr uint16_t Id = XCOMPAR_PAREKF_POSAIDSTDDEVTHR;
};
template<>
struct ParameterTraits<XCOMParEKF_STOREDATT> {
    static constexpr uint16_t Id = XCOMPAR_PAREKF_STOREDATT;
};
template<>
struct ParameterTraits<XCOMParEKF_ODOMETER> {
    static constexpr uint16_t Id = XCOMPAR_PAREKF_ODOMETER;
};
template<>
struct ParameterTraits<XCOMParEKF_ODOBOGIE> {
    static constexpr uint16_t Id = XCOMPAR_PAREKF_ODOBOGIE;
};
template<>
struct ParameterTraits<XCOMParEKF_GNSSLEVERARMEST> {
    static constexpr uint16_t Id = XCOMPAR_PAREKF_GNSSLEVERARMEST;
};
template<>
struct ParameterTraits<XCOMParEKF_GNSSAIDRATE> {
    static constexpr uint16_t Id = XCOMPAR_PAREKF_GNSSAIDRATE;
};
template<>
struct ParameterTraits<XCOMParEKF_KINALIGNTHR> {
    static constexpr uint16_t Id = XCOMPAR_PAREKF_KINALIGNTHR;
};
template<>
struct ParameterTraits<XCOMParEKF_GNSSPDOP> {
    static constexpr uint16_t Id = XCOMPAR_PAREKF_GNSSPDOP;
};
template<>
struct ParameterTraits<XCOMParEKF_DUALANTAID> {
    static constexpr uint16_t Id = XCOMPAR_PAREKF_DUALANTAID;
};
template<>
struct ParameterTraits<XCOMParEKF_STARTUPV2> {
    static constexpr uint16_t Id = XCOMPAR_PAREKF_STARTUPV2;
};
template<>
struct ParameterTraits<XCOMParEKF_MAGATTAID> {
    static constexpr uint16_t Id = XCOMPAR_PAREKF_MAGATTAID;
};
template<>
struct ParameterTraits<XCOMParEKF_MADCAID> {
    static constexpr uint16_t Id = XCOMPAR_PAREKF_MADCAID;
};
template<>
struct ParameterTraits<XCOMParEKF_ALIGNMENT> {
    static constexpr uint16_t Id = XCOMPAR_PAREKF_ALIGNMENT;
};
template<>
struct ParameterTraits<XCOMParEKF_GRAVITYAIDING> {
    static constexpr uint16_t Id = XCOMPAR_PAREKF_GRAVITYAIDING;
};
template<>
struct ParameterTraits<XCOMParEKF_FEEDBACK> {
    static constexpr uint16_t Id = XCOMPAR_PAREKF_FEEDBACK;
};
template<>
struct ParameterTraits<XCOMParEKF_ZARU> {
    static constexpr uint16_t Id = XCOMPAR_PAREKF_ZARU;
};
template<>
struct ParameterTraits<XCOMParEKF_ZUPTCALIB> {
    static constexpr uint16_t Id = XCOMPAR_PAREKF_ZUPTCALIB;
};
template<>
struct ParameterTraits<XCOMParEKF_STATEFREEZE> {
    static constexpr uint16_t Id = XCOMPAR_PAREKF_STATEFREEZE;
};
template<>
struct ParameterTraits<XCOMParEKF_RECOVERY> {
    static constexpr uint16_t Id = XCOMPAR_PAREKF_RECOVERY;
};
template<>
struct ParameterTraits<XCOMParEKF_STOREDVALSTDDEV> {
    static constexpr uint16_t Id = XCOMPAR_PAREKF_STOREDVALSTDDEV;
};
template<>
struct ParameterTraits<XCOMParEKF_ODOREVDETECT> {
    static constexpr uint16_t Id = XCOMPAR_PAREKF_ODOREVDETECT;
};
template<>
struct ParameterTraits<XCOMParEKF_PSEUDOPOS> {
    static constexpr uint16_t Id = XCOMPAR_PAREKF_PSEUDOPOS;
};
template<>
struct ParameterTraits<XCOMParEKF_FHUPD> {
    static constexpr uint16_t Id = XCOMPAR_PAREKF_FHUPD;
};
template<>
struct ParameterTraits<XCOMParEKF_FORCEDZUPT> {
    static constexpr uint16_t Id = XCOMPAR_PAREKF_FORCEDZUPT;
};
template<>
struct ParameterTraits<XCOMParEKF_ZARUSTDDEV> {
    static constexpr uint16_t Id = XCOMPAR_PAREKF_ZARUSTDDEV;
};
template<>
struct ParameterTraits<XCOMParEKF_FPUPD> {
    static constexpr uint16_t Id = XCOMPAR_PAREKF_FPUPD;
};
template<>
struct ParameterTraits<XCOMParEKF_SLEWMODE> {
    static constexpr uint16_t Id = XCOMPAR_PAREKF_SLEWMODE;
};
template<>
struct ParameterTraits<XCOMParEKF_ODOLEVERARMEST> {
    static constexpr uint16_t Id = XCOMPAR_PAREKF_ODOLEVERARMEST;
};
template<>
struct ParameterTraits<XCOMParEKF_REFFRAME> {
    static constexpr uint16_t Id = XCOMPAR_PAREKF_REFFRAME;
};
template<>
struct ParameterTraits<XCOMParEKF_AUTOHEIGHT> {
    static constexpr uint16_t Id = XCOMPAR_PAREKF_AUTOHEIGHT;
};
template<>
struct ParameterTraits<XCOMParEKF_ZUPTREQUEST> {
    static constexpr uint16_t Id = XCOMPAR_PAREKF_ZUPTREQUEST;
};
template<>
struct ParameterTraits<XCOMParEKF_POSUPDATEREQUEST> {
    static constexpr uint16_t Id = XCOMPAR_PAREKF_POSUPDATEREQUEST;
};
template<>
struct ParameterTraits<XCOMParEKF_STOREDALIGNMODE> {
    static constexpr uint16_t Id = XCOMPAR_PAREKF_STOREDALIGNMODE;
};
template<>
struct ParameterTraits<XCOMParEKF_EXTAIDREFFRAME> {
    static constexpr uint16_t Id = XCOMPAR_PAREKF_EXTAIDREFFRAME;
};
template<>
struct ParameterTraits<XCOMParEKF_IMUCONFIG2> {
    static constexpr uint16_t Id = XCOMPAR_PAREKF_IMUCONFIG2;
};
template<>
struct ParameterTraits<XCOMParDAT_POS> {
    static constexpr uint16_t Id = XCOMPAR_PARDAT_POS;
};
template<>
struct ParameterTraits<XCOMParDAT_VEL> {
    static constexpr uint16_t Id = XCOMPAR_PARDAT_VEL;
};
template<>
struct ParameterTraits<XCOMParDAT_IMU> {
    static constexpr uint16_t Id = XCOMPAR_PARDAT_IMU;
};
template<>
struct ParameterTraits<XCOMParDAT_SYSSTAT> {
    static constexpr uint16_t Id = XCOMPAR_PARDAT_SYSSTAT;
};
template<>
struct ParameterTraits<XCOMParDAT_REFFRAME> {
    static constexpr uint16_t Id = XCOMPAR_PARDAT_REFFRAME;
};
template<>
struct ParameterTraits<XCOMParXCOM_SERIALPORT> {
    static constexpr uint16_t Id = XCOMPAR_PARXCOM_SERIALPORT;
};
template<>
struct ParameterTraits<XCOMParXCOM_NETCONFIG> {
    static constexpr uint16_t Id = XCOMPAR_PARXCOM_NETCONFIG;
};
template<>
struct ParameterTraits<XCOMParXCOM_LOGLIST> {
    static constexpr uint16_t Id = XCOMPAR_PARXCOM_LOGLIST;
};
template<>
struct ParameterTraits<XCOMParXCOM_AUTOSTART> {
    static constexpr uint16_t Id = XCOMPAR_PARXCOM_AUTOSTART;
};
template<>
struct ParameterTraits<XCOMParXCOM_NTRIP> {
    static constexpr uint16_t Id = XCOMPAR_PARXCOM_NTRIP;
};
template<>
struct ParameterTraits<XCOMParXCOM_POSTPROC> {
    static constexpr uint16_t Id = XCOMPAR_PARXCOM_POSTPROC;
};
template<>
struct ParameterTraits<XCOMParXCOM_UDPCONFIG> {
    static constexpr uint16_t Id = XCOMPAR_PARXCOM_UDPCONFIG;
};
template<>
struct ParameterTraits<XCOMParXCOM_DUMPENABLE> {
    static constexpr uint16_t Id = XCOMPAR_PARXCOM_DUMPENABLE;
};
template<>
struct ParameterTraits<XCOMParXCOM_MIGRATOR> {
    static constexpr uint16_t Id = XCOMPAR_PARXCOM_MIGRATOR;
};
template<>
struct ParameterTraits<XCOMParXCOM_TCPKEEPAL> {
    static constexpr uint16_t Id = XCOMPAR_PARXCOM_TCPKEEPAL;
};
template<>
struct ParameterTraits<XCOMParXCOM_CANGATEWAY> {
    static constexpr uint16_t Id = XCOMPAR_PARXCOM_CANGATEWAY;
};
template<>
struct ParameterTraits<XCOMParXCOM_DEFAULTIP> {
    static constexpr uint16_t Id = XCOMPAR_PARXCOM_DEFAULTIP;
};
template<>
struct ParameterTraits<XCOMParXCOM_LOGLIST2> {
    static constexpr uint16_t Id = XCOMPAR_PARXCOM_LOGLIST2;
};
template<>
struct ParameterTraits<XCOMParXCOM_CLIENT> {
    static constexpr uint16_t Id = XCOMPAR_PARXCOM_CLIENT;
};
template<>
struct ParameterTraits<XCOMParXCOM_INTERFACE> {
    static constexpr uint16_t Id = XCOMPAR_PARXCOM_INTERFACE;
};
template<>
struct ParameterTraits<XCOMParXCOM_PLUGINVERSION> {
    static constexpr uint16_t Id = XCOMPAR_PARXCOM_PLUGINVERSION;
};
template<>
struct ParameterTraits<XCOMParXCOM_NTRIPV2> {
    static constexpr uint16_t Id = XCOMPAR_PARXCOM_NTRIPV2;
};
template<>
struct ParameterTraits<XCOMParXCOM_ABDVERSION> {
    static constexpr uint16_t Id = XCOMPAR_PARXCOM_ABDVERSION;
};
template<>
struct ParameterTraits<XCOMParODO_SCF> {
    static constexpr uint16_t Id = XCOMPAR_PARODO_SCF;
};
template<>
struct ParameterTraits<XCOMParODO_TIMEOUT> {
    static constexpr uint16_t Id = XCOMPAR_PARODO_TIMEOUT;
};
template<>
struct ParameterTraits<XCOMParODO_MODE> {
    static constexpr uint16_t Id = XCOMPAR_PARODO_MODE;
};
template<>
struct ParameterTraits<XCOMParODO_LEVERARM> {
    static constexpr uint16_t Id = XCOMPAR_PARODO_LEVERARM;
};
template<>
struct ParameterTraits<XCOMParODO_VELSTDDEV> {
    static constexpr uint16_t Id = XCOMPAR_PARODO_VELSTDDEV;
};
template<>
struct ParameterTraits<XCOMParODO_DIRECTION> {
    static constexpr uint16_t Id = XCOMPAR_PARODO_DIRECTION;
};
template<>
struct ParameterTraits<XCOMParODO_CONSTRAINTS> {
    static constexpr uint16_t Id = XCOMPAR_PARODO_CONSTRAINTS;
};
template<>
struct ParameterTraits<XCOMParODO_RATE> {
    static constexpr uint16_t Id = XCOMPAR_PARODO_RATE;
};
template<>
struct ParameterTraits<XCOMParODO_THR> {
    static constexpr uint16_t Id = XCOMPAR_PARODO_THR;
};
template<>
struct ParameterTraits<XCOMParODO_INVERTER> {
    static constexpr uint16_t Id = XCOMPAR_PARODO_INVERTER;
};
template<>
struct ParameterTraits<XCOMParODO_SWAP> {
    static constexpr uint16_t Id = XCOMPAR_PARODO_SWAP;
};
template<>
struct ParameterTraits<XCOMParODO_PPDDIVIDER> {
    static constexpr uint16_t Id = XCOMPAR_PARODO_PPDDIVIDER;
};
template<>
struct ParameterTraits<XCOMParODO_MODE2> {
    static constexpr uint16_t Id = XCOMPAR_PARODO_MODE2;
};
template<>
struct ParameterTraits<XCOMParODO_LATENCY> {
    static constexpr uint16_t Id = XCOMPAR_PARODO_LATENCY;
};
template<>
struct ParameterTraits<XCOMParODO_VELSIGN> {
    static constexpr uint16_t Id = XCOMPAR_PARODO_VELSIGN;
};
template<>
struct ParameterTraits<XCOMParNMEA0183_COM> {
    static constexpr uint16_t Id = XCOMPAR_PARNMEA0183_COM;
};
template<>
struct ParameterTraits<XCOMParNMEA0183_ENABLE> {
    static constexpr uint16_t Id = XCOMPAR_PARNMEA0183_ENABLE;
};
template<>
struct ParameterTraits<XCOMParNMEA0183_TXMASK> {
    static constexpr uint16_t Id = XCOMPAR_PARNMEA0183_TXMASK;
};
template<>
struct ParameterTraits<XCOMParNMEA0183_RATE> {
    static constexpr uint16_t Id = XCOMPAR_PARNMEA0183_RATE;
};
template<>
struct ParameterTraits<XCOMParNMEA0183_UDP> {
    static constexpr uint16_t Id = XCOMPAR_PARNMEA0183_UDP;
};
template<>
struct ParameterTraits<XCOMParNMEA0183_VTGSELECT> {
    static constexpr uint16_t Id = XCOMPAR_PARNMEA0183_VTGSELECT;
};
template<>
struct ParameterTraits<XCOMParNMEA0183_PRECISION> {
    static constexpr uint16_t Id = XCOMPAR_PARNMEA0183_PRECISION;
};
template<>
struct ParameterTraits<XCOMParNMEA0183_LOCALZONE> {
    static constexpr uint16_t Id = XCOMPAR_PARNMEA0183_LOCALZONE;
};
template<>
struct ParameterTraits<XCOMParARINC825_PORT> {
    static constexpr uint16_t Id = XCOMPAR_ARINC825_PORT;
};
template<>
struct ParameterTraits<XCOMParARINC825_BAUD> {
    static constexpr uint16_t Id = XCOMPAR_ARINC825_BAUD;
};
template<>
struct ParameterTraits<XCOMParARINC825_ENABLE> {
    static constexpr uint16_t Id = XCOMPAR_ARINC825_ENABLE;
};
template<>
struct ParameterTraits<XCOMParARINC825_BUSRECOVERY> {
    static constexpr uint16_t Id = XCOMPAR_ARINC825_BUSRECOVERY;
};
template<>
struct ParameterTraits<XCOMParARINC825_RESETSTATUS> {
    static constexpr uint16_t Id = XCOMPAR_ARINC825_RESETSTATUS;
};
template<>
struct ParameterTraits<XCOMParARINC825_SCALEFACTOR> {
    static constexpr uint16_t Id = XCOMPAR_ARINC825_SCALEFACTOR;
};
template<>
struct ParameterTraits<XCOMParARINC825_EVENTMASK> {
    static constexpr uint16_t Id = XCOMPAR_ARINC825_EVENTMASK;
};
template<>
struct ParameterTraits<XCOMParARINC825_GENERALCAN> {
    static constexpr uint16_t Id = XCOMPAR_ARINC825_GENERALCAN;
};
template<>
struct ParameterTraits<XCOMParARINC825_PROTOCOL> {
    static constexpr uint16_t Id = XCOMPAR_ARINC825_PROTOCOL;
};
template<>
struct ParameterTraits<XCOMParARINC825_OBDII> {
    static constexpr uint16_t Id = XCOMPAR_ARINC825_OBDII;
};
template<>
struct ParameterTraits<XCOMParARINC429_CONFIG> {
    static constexpr uint16_t Id = XCOMPAR_PARARINC429_CONFIG;
};
template<>
struct ParameterTraits<XCOMParIO_SYNCOUT> {
    static constexpr uint16_t Id = XCOMPAR_PARIO_SYNCOUT;
};
template<>
struct ParameterTraits<XCOMParIO_SYNCOUT2> {
    static constexpr uint16_t Id = XCOMPAR_PARIO_SYNCOUT2;
};
template<>
struct ParameterTraits<XCOMParIO_SYNCIN> {
    static constexpr uint16_t Id = XCOMPAR_PARIO_SYNCIN;
};
template<>
struct ParameterTraits<XCOMParSCU_NADIR> {
    static constexpr uint16_t Id = XCOMPAR_PARSCU_NADIR;
};
template<>
struct ParameterTraits<XCOMParTIMESYNC_NTP> {
    static constexpr uint16_t Id = XCOMPAR_PARTIMESYNC_NTP;
};
template<>
struct ParameterTraits<XCOMParCAN_DEVICECONFIG> {
    static constexpr uint16_t Id = XCOMPAR_PARCAN_DEVICECONFIG;
};
template<>
struct ParameterTraits<XCOMParCAN_SIMPLECAN> {
    static constexpr uint16_t Id = XCOMPAR_PARCAN_SIMPLECAN;
};
template<>
struct ParameterTraits<XCOMParCAN_BUSTERMINATION> {
    static constexpr uint16_t Id = XCOMPAR_PARCAN_BUSTERMINATION;
};
template<>
struct ParameterTraits<XCOMParCAN_VRUCAN> {
    static constexpr uint16_t Id = XCOMPAR_PARCAN_VRUCAN;
};
template<>
struct ParameterTraits<XCOMParPLUGIN_GENERIC> {
    static constexpr uint16_t Id = XCOMPAR_PARPLUGIN_GENERIC;
};
template<>
struct ParameterTraits<XCOMParEXTSENSOR_NMEA0183> {
    static constexpr uint16_t Id = XCOMPAR_EXTSENSOR_NMEA0183;
};
template<>
struct ParameterTraits<XCOMParEXTSENSOR_VIPS> {
    static constexpr uint16_t Id = XCOMPAR_EXTSENSOR_VIPS;
};
template<>
struct ParameterTraits<XCOMParEXTSENSOR_VBODYMISALIGN> {
    static constexpr uint16_t Id = XCOMPAR_EXTSENSOR_VBODYMISALIGN;
};
#endif
