#ifndef LIBXCOM_MESSAGE_TRAITS_H
#define LIBXCOM_MESSAGE_TRAITS_H

#include <cmath>
#include <ixcom/XCOMdat.h>
#include <type_traits>

// This file is automatically generated, DO NOT EDIT.

template<typename>
struct MessageTraits;

template<>
struct MessageTraits<XCOMmsg_IMURAW> {
    static constexpr uint8_t Id = XCOM_MSGID_IMURAW;
};

template<>
struct MessageTraits<XCOMmsg_IMUCORR> {
    static constexpr uint8_t Id = XCOM_MSGID_IMUCORR;
};

template<>
struct MessageTraits<XCOMmsg_IMUCOMP> {
    static constexpr uint8_t Id = XCOM_MSGID_IMUCOMP;
};

template<>
struct MessageTraits<XCOMmsg_RAWDATA> {
    static constexpr uint8_t Id = XCOM_MSGID_RAWDATA;
};

template<>
struct MessageTraits<XCOMmsg_OMGINT> {
    static constexpr uint8_t Id = XCOM_MSGID_OMGINT;
};

template<>
struct MessageTraits<XCOMmsg_OMGDOT> {
    static constexpr uint8_t Id = XCOM_MSGID_OMGDOT;
};

template<>
struct MessageTraits<XCOMmsg_LOADFACTOR> {
    static constexpr uint8_t Id = XCOM_MSGID_LOADFACTOR;
};

template<>
struct MessageTraits<XCOMmsg_TEMPERATURE> {
    static constexpr uint8_t Id = XCOM_MSGID_TEMPERATURE;
};

template<>
struct MessageTraits<XCOMmsg_POWER> {
    static constexpr uint8_t Id = XCOM_MSGID_POWER;
};

template<>
struct MessageTraits<XCOMmsg_TIME> {
    static constexpr uint8_t Id = XCOM_MSGID_TIME;
};

template<>
struct MessageTraits<XCOMmsg_EVENTTIME> {
    static constexpr uint8_t Id = XCOM_MSGID_EVENTTIME;
};

template<>
struct MessageTraits<XCOMmsg_IMUFILTERED> {
    static constexpr uint8_t Id = XCOM_MSGID_IMUFILTERED;
};

template<>
struct MessageTraits<XCOMmsg_INSSOL> {
    static constexpr uint8_t Id = XCOM_MSGID_INSSOL;
};

template<>
struct MessageTraits<XCOMmsg_INSSOLECEF> {
    static constexpr uint8_t Id = XCOM_MSGID_INSSOLECEF;
};

template<>
struct MessageTraits<XCOMmsg_INSRPY> {
    static constexpr uint8_t Id = XCOM_MSGID_INSRPY;
};

template<>
struct MessageTraits<XCOMmsg_INSDCM> {
    static constexpr uint8_t Id = XCOM_MSGID_INSDCM;
};

template<>
struct MessageTraits<XCOMmsg_INSQUAT> {
    static constexpr uint8_t Id = XCOM_MSGID_INSQUAT;
};

template<>
struct MessageTraits<XCOMmsg_INSVELNED> {
    static constexpr uint8_t Id = XCOM_MSGID_INSVELNED;
};

template<>
struct MessageTraits<XCOMmsg_INSVELENU> {
    static constexpr uint8_t Id = XCOM_MSGID_INSVELENU;
};

template<>
struct MessageTraits<XCOMmsg_INSVELECEF> {
    static constexpr uint8_t Id = XCOM_MSGID_INSVELECEF;
};

template<>
struct MessageTraits<XCOMmsg_INSVELBODY> {
    static constexpr uint8_t Id = XCOM_MSGID_INSVELBODY;
};

template<>
struct MessageTraits<XCOMmsg_INSPOSLLH> {
    static constexpr uint8_t Id = XCOM_MSGID_INSPOSLLH;
};

template<>
struct MessageTraits<XCOMmsg_INSPOSECEF> {
    static constexpr uint8_t Id = XCOM_MSGID_INSPOSECEF;
};

template<>
struct MessageTraits<XCOMmsg_INSPOSUTM> {
    static constexpr uint8_t Id = XCOM_MSGID_INSPOSUTM;
};

template<>
struct MessageTraits<XCOMmsg_INSGNDSPEED> {
    static constexpr uint8_t Id = XCOM_MSGID_INSGNDSPEED;
};

template<>
struct MessageTraits<XCOMmsg_INSTRACKACC> {
    static constexpr uint8_t Id = XCOM_MSGID_INSTRACKACC;
};

template<>
struct MessageTraits<XCOMmsg_INSMAGHDG> {
    static constexpr uint8_t Id = XCOM_MSGID_INSMAGHDG;
};

template<>
struct MessageTraits<XCOMmsg_INSMGRS> {
    static constexpr uint8_t Id = XCOM_MSGID_INSMGRS;
};

template<>
struct MessageTraits<XCOMmsg_INSRPYRATE> {
    static constexpr uint8_t Id = XCOM_MSGID_INSRPYRATE;
};

template<>
struct MessageTraits<XCOMmsg_ACCNED> {
    static constexpr uint8_t Id = XCOM_MSGID_ACCNED;
};

template<>
struct MessageTraits<XCOMmsg_UNIXTIME> {
    static constexpr uint8_t Id = XCOM_MSGID_UNIXTIME;
};

template<>
struct MessageTraits<XCOMmsg_INSWANDERAZIMUTH> {
    static constexpr uint8_t Id = XCOM_MSGID_INSWANDERAZIMUTH;
};

template<>
struct MessageTraits<XCOMmsg_JERKNED> {
    static constexpr uint8_t Id = XCOM_MSGID_JERKNED;
};

template<>
struct MessageTraits<XCOMmsg_EKFSTDDEV> {
    static constexpr uint8_t Id = XCOM_MSGID_EKFSTDDEV;
};

template<>
struct MessageTraits<XCOMmsg_EKFSTDDEV2> {
    static constexpr uint8_t Id = XCOM_MSGID_EKFSTDDEV2;
};

template<>
struct MessageTraits<XCOMmsg_EKFSTDDEV3> {
    static constexpr uint8_t Id = XCOM_MSGID_EKFSTDDEV3;
};

template<>
struct MessageTraits<XCOMmsg_EKFERROR> {
    static constexpr uint8_t Id = XCOM_MSGID_EKFERROR;
};

template<>
struct MessageTraits<XCOMmsg_EKFERROR2> {
    static constexpr uint8_t Id = XCOM_MSGID_EKFERROR2;
};

template<>
struct MessageTraits<XCOMmsg_EKFPOSCOVAR> {
    static constexpr uint8_t Id = XCOM_MSGID_EKFPOSCOVAR;
};

template<>
struct MessageTraits<XCOMmsg_EKFTIGHTLY> {
    static constexpr uint8_t Id = XCOM_MSGID_EKFTIGHTLY;
};

template<>
struct MessageTraits<XCOMmsg_EKFSTDDEVECEF> {
    static constexpr uint8_t Id = XCOM_MSGID_EKFSTDDEVECEF;
};

template<>
struct MessageTraits<XCOMmsg_GNSSSOL> {
    static constexpr uint8_t Id = XCOM_MSGID_GNSSSOL;
};

template<>
struct MessageTraits<XCOMmsg_GNSSTIME> {
    static constexpr uint8_t Id = XCOM_MSGID_GNSSTIME;
};

template<>
struct MessageTraits<XCOMmsg_GNSSSATINFO> {
    static constexpr uint8_t Id = XCOM_MSGID_GNSSSATINFO;
};

template<>
struct MessageTraits<XCOMmsg_GNSSHDG> {
    static constexpr uint8_t Id = XCOM_MSGID_GNSSHDG;
};

template<>
struct MessageTraits<XCOMmsg_GNSSLEVERARM> {
    static constexpr uint8_t Id = XCOM_MSGID_GNSSLEVERARM;
};

template<>
struct MessageTraits<XCOMmsg_GNSSVOTER> {
    static constexpr uint8_t Id = XCOM_MSGID_GNSSVOTER;
};

template<>
struct MessageTraits<XCOMmsg_GNSSSATINF> {
    static constexpr uint8_t Id = XCOM_MSGID_GNSSSATINF;
};

template<>
struct MessageTraits<XCOMmsg_GNSSSTREAM> {
    static constexpr uint8_t Id = XCOM_MSGID_GNSSSTREAM;
};

template<>
struct MessageTraits<XCOMmsg_GNSSOBSSTREAM> {
    static constexpr uint8_t Id = XCOM_MSGID_GNSSOBSSTREAM;
};

template<>
struct MessageTraits<XCOMmsg_GNSSDOP> {
    static constexpr uint8_t Id = XCOM_MSGID_GNSSDOP;
};

template<>
struct MessageTraits<XCOMmsg_GNSSHWMON> {
    static constexpr uint8_t Id = XCOM_MSGID_GNSSHWMON;
};

template<>
struct MessageTraits<XCOMmsg_PORTSTATS> {
    static constexpr uint8_t Id = XCOM_MSGID_PORTSTATS;
};

template<>
struct MessageTraits<XCOMmsg_GNSSPOSECEF> {
    static constexpr uint8_t Id = XCOM_MSGID_GNSSPOSECEF;
};

template<>
struct MessageTraits<XCOMmsg_GNSSVELECEF> {
    static constexpr uint8_t Id = XCOM_MSGID_GNSSVELECEF;
};

template<>
struct MessageTraits<XCOMmsg_MAGDATA2> {
    static constexpr uint8_t Id = XCOM_MSGID_MAGDATA2;
};

template<>
struct MessageTraits<XCOMmsg_GREENLIGHTLOCAL> {
    static constexpr uint8_t Id = XCOM_MSGID_GREENLIGHTLOCAL;
};

template<>
struct MessageTraits<XCOMmsg_GREENLIGHTSMARTPHONE> {
    static constexpr uint8_t Id = XCOM_MSGID_GREENLIGHTSMARTPHONE;
};

template<>
struct MessageTraits<XCOMmsg_WHEELDATA> {
    static constexpr uint8_t Id = XCOM_MSGID_WHEELDATA;
};

template<>
struct MessageTraits<XCOMmsg_AIRDATA> {
    static constexpr uint8_t Id = XCOM_MSGID_AIRDATA;
};

template<>
struct MessageTraits<XCOMmsg_MAGDATA> {
    static constexpr uint8_t Id = XCOM_MSGID_MAGDATA;
};

template<>
struct MessageTraits<XCOMmsg_ADC24DATA> {
    static constexpr uint8_t Id = XCOM_MSGID_ADC24DATA;
};

template<>
struct MessageTraits<XCOMmsg_CSACDATA> {
    static constexpr uint8_t Id = XCOM_MSGID_CSACDATA;
};

template<>
struct MessageTraits<XCOMmsg_SYSSTAT> {
    static constexpr uint8_t Id = XCOM_MSGID_SYSSTAT;
};

template<>
struct MessageTraits<XCOMmsg_CANSTATUS> {
    static constexpr uint8_t Id = XCOM_MSGID_CANSTATUS;
};

template<>
struct MessageTraits<XCOMmsg_STATFPGA> {
    static constexpr uint8_t Id = XCOM_MSGID_STATFPGA;
};

template<>
struct MessageTraits<XCOMmsg_ADC24STATUS> {
    static constexpr uint8_t Id = XCOM_MSGID_ADC24STATUS;
};

template<>
struct MessageTraits<XCOMmsg_ARINC429STAT> {
    static constexpr uint8_t Id = XCOM_MSGID_ARINC429STAT;
};

template<>
struct MessageTraits<XCOMmsg_MONITOR> {
    static constexpr uint8_t Id = XCOM_MSGID_MONITOR;
};

template<>
struct MessageTraits<XCOMmsg_MVCSLAVE> {
    static constexpr uint8_t Id = XCOM_MSGID_MVCSLAVE;
};

template<>
struct MessageTraits<XCOMmsg_MVCDATA> {
    static constexpr uint8_t Id = XCOM_MSGID_MVCDATA;
};

template<>
struct MessageTraits<XCOMmsg_POSTPROC> {
    static constexpr uint8_t Id = XCOM_MSGID_POSTPROC;
};

template<>
struct MessageTraits<XCOMmsg_NTRIPSTATUS> {
    static constexpr uint8_t Id = XCOM_MSGID_NTRIPSTATUS;
};

template<>
struct MessageTraits<XCOMmsg_ABDPROTOCOL> {
    static constexpr uint8_t Id = XCOM_MSGID_ABDPROTOCOL;
};

template<>
struct MessageTraits<XCOMmsg_CANGATEWAY> {
    static constexpr uint8_t Id = XCOM_MSGID_CANGATEWAY;
};

template<>
struct MessageTraits<XCOMmsg_CANSTATUS2> {
    static constexpr uint8_t Id = XCOM_MSGID_CANSTATUS2;
};

template<>
struct MessageTraits<XCOMmsg_EXTPOSLLH> {
    static constexpr uint8_t Id = XCOM_MSGID_EXTPOSLLH;
};

template<>
struct MessageTraits<XCOMmsg_EXTVELNED> {
    static constexpr uint8_t Id = XCOM_MSGID_EXTVELNED;
};

template<>
struct MessageTraits<XCOMmsg_EXTVELBODY> {
    static constexpr uint8_t Id = XCOM_MSGID_EXTVELBODY;
};

template<>
struct MessageTraits<XCOMmsg_EXTSTREAM> {
    static constexpr uint8_t Id = XCOM_MSGID_EXTSTREAM;
};

template<>
struct MessageTraits<XCOMmsg_EXTHEIGHT> {
    static constexpr uint8_t Id = XCOM_MSGID_EXTHEIGHT;
};

template<>
struct MessageTraits<XCOMmsg_EXTHEADING> {
    static constexpr uint8_t Id = XCOM_MSGID_EXTHEADING;
};

template<>
struct MessageTraits<XCOMmsg_SYNCCOUNTER> {
    static constexpr uint8_t Id = XCOM_MSGID_SYNCCOUNTER;
};

template<>
struct MessageTraits<XCOMmsg_ODOLEVERARM> {
    static constexpr uint8_t Id = XCOM_MSGID_ODOLEVERARM;
};

template<>
struct MessageTraits<XCOMmsg_BATSTAT2> {
    static constexpr uint8_t Id = XCOM_MSGID_BATSTAT2;
};

template<>
struct MessageTraits<XCOMmsg_EKFSTATEXT> {
    static constexpr uint8_t Id = XCOM_MSGID_EKFSTATEXT;
};

template<>
struct MessageTraits<XCOMmsg_IPVAS> {
    static constexpr uint8_t Id = XCOM_MSGID_IPVAS;
};

#endif
